version: "3.7"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8-debian
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quickpoll
    ports:
      - "3306:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci",
        "--lower-case-table-names=1",
      ]
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
