name: Lint Frontend

on:
    push:
        paths:
            - "frontend/**"
            - ".github/workflows/build-frontend.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i
      working-directory: ./frontend

    - name: Run Next.js Linter
      run: pnpm lint
      working-directory: ./frontend

    - name: Build Next.js app
      run: pnpm build
      working-directory: ./frontend