name: Lint Frontend

on:
    push:
        paths:
            - "frontend/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run Next.js Linter
      run: npm run lint
      working-directory: ./frontend
